apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.backend.env.jwtSecret | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: {{ .Values.backend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: MONGO_URI
              value: {{ .Values.backend.env.mongoUri | quote }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
            - name: JWT_EXPIRES_IN
              value: {{ .Values.backend.env.jwtExpiresIn | quote }}
            - name: NODE_ENV
              value: {{ .Values.backend.env.nodeEnv | quote }}
            - name: PORT
              value: {{ .Values.backend.port | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: todo-backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
